steps:
  # Build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/${PROJECT_ID}/eruption-rate-analysis/image:${SHORT_SHA}', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/${PROJECT_ID}/eruption-rate-analysis/image:${SHORT_SHA}', '.']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - run
      - deploy
      - eruption-rate-analysis
      - --image
      - europe-west4-docker.pkg.dev/${PROJECT_ID}/eruption-rate-analysis/image:${SHORT_SHA}
      - --platform
      - managed
      - --region
      - europe-west4
      - --allow-unauthenticated
      - --port
      - '8080'

images:
  - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/eruption-rate-analysis/image:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
