steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/eruption-rate-analysis', '.']

# Step 2: Push the image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/eruption-rate-analysis']

# Step 3: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - eruption-rate-analysis  # Name of your Cloud Run service
    - --image
    - gcr.io/$PROJECT_ID/eruption-rate-analysis
    - --region
    - europe-west4
    - --platform
    - managed
    - --allow-unauthenticated
    - --port
    - '8080'

# Substitutions can be used for parameters like $PROJECT_ID
substitutions:
  _SERVICE_NAME: 'eruption-rate-analysis'

images:
- 'gcr.io/$PROJECT_ID/eruption-rate-analysis'

