steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_SERVICE_NAME/your-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_SERVICE_NAME/your-app']

images:
  - 'gcr.io/$_SERVICE_NAME/your-app'
