steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - '-t'
      - 'gcr.io/$_SERVICE_NAME/your-app'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$_SERVICE_NAME/your-app'
  - name: gcr.io/googlecom/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - 'gcr.io/$_SERVICE_NAME/your-app'
    entrypoint: gcloud
timeout: 1200s
images:
  - 'gcr.io/$_SERVICE_NAME/your-app'
